Add create docker images on tag
plonegovbr/portal.buildout pull request #100
Opened 2017-11-27 20:14 UTC by caduvieira

2017-11-27 20:18 UTC, hvelarde commented on .travis.yml
> -  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
o @idgserpro quer esse comentário ai.

2017-11-27 20:19 UTC, hvelarde commented on .travis.yml
> -# FIXME: we have isolation issues running tests
eu quero esse comentário ai.

2017-11-27 20:29 UTC, caduvieira commented on .travis.yml
> -  # XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
quando usei o gem travis para adicionar os envs encriptados ele removeu todos os comentários não sei por que

2017-11-28 11:30 UTC, idgserpro requested changes

2017-11-28 11:30 UTC, idgserpro commented on .travis.yml
> -  # TODO: update https://github.com/plonegovbr/portalpadrao.release/blob/master/README.md
Favor não remover o comentário.

2017-11-28 11:30 UTC, idgserpro commented on .travis.yml
> +  buildout.cfg
O `buildout.cfg` tem que ficar na linda de cima.

2017-11-28 11:30 UTC, idgserpro commented on .travis.yml
> +# XXX: use an older Firefox ESR as we are stuck with selenium = 2.53.5
Remover os espaços.

2017-11-28 11:30 UTC, idgserpro commented on .travis.yml
> +# arquivo onde procura a string, trocando bin/instance por parts/instance.site.py
Remover os espaços.

2017-11-28 11:32 UTC, idgserpro commented on .travis.yml
> +#      https://github.com/SeleniumHQ/selenium/issues/2739#issuecomment-249482533
Indentar o comentário.

2017-12-05 19:23 UTC, idgserpro commented
@caduvieira os testes estão falhando.

2018-09-21 23:31 UTC, hvelarde commented
@caduvieira tu vai continuar com isso aqui?

2018-10-31 22:07 UTC, caduvieira commented
Estou sem tempo para continuar. Pode fechar

2018-10-31 22:10 UTC, hvelarde commented
vou deixar aberto, tal vez alguém se anima continuar.

2019-06-05 17:37 UTC, caduvieira commented
Como posso corrigir essa questão da barra?

2019-06-06 19:02 UTC, idgserpro commented
O código da barra no `brasil.gov.barra` está diferente do código da barra na internet. É necessário atualizar o código da barra no `brasil.gov.barra`.

Só de rodar o buildout do `brasil.gov.barra` ele atualiza o código da barra.

Isso foi feito, por exemplo nesse commit:

https://github.com/plonegovbr/brasil.gov.barra/commit/4bdcc702290e32d896636e2df5de3f10266be305

2021-09-02 13:18 UTC, closed without merging